language: python
dist: xenial
services:
  - docker

# * run various Python versions tests on MySQL 5.7
# * run all MySQL versions tests on Python 3.7
# @see https://docs.travis-ci.com/user/customizing-the-build/#Explicitly-Including-Jobs
matrix:
  include:
    - python: "3.6"
      env: DOCKER_IMAGE=mysql:5.7
    - python: "3.7"
      env: DOCKER_IMAGE=mysql:5.7
    - python: "3.8"
      env: DOCKER_IMAGE=mysql:5.7

    # @see https://hub.docker.com/_/mysql/
    # @see https://www.fromdual.com/support-for-mysql-from-oracle
    - python: "3.7"
      env: DOCKER_IMAGE=mysql:8.0.3
    # @see https://hub.docker.com/_/mariadb/
    - python: "3.7"
      env: DOCKER_IMAGE=mariadb:10.1
    - python: "3.7"
      env: DOCKER_IMAGE=mariadb:10.2

before_script:
  # @see https://medium.com/@mtparet/install-mysql-server-5-7-on-travis-96f2ebc0f339
  # @see https://hub.docker.com/_/mysql/
  - sudo service mysql stop  # stop any running MySQL server
  - sudo docker run -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d -p 3306:3306 $DOCKER_IMAGE
  - ./wait_for_mysql.sh
  - sudo docker ps
  # set up a database
  - mysql --protocol=tcp -u root -v < setup.sql
  - "./sql/populate.sh" # import the test schema files
  - mysql --protocol=tcp -uindex_digest -pqwerty index_digest -v -e '\s; SHOW TABLES; SHOW DATABASES;'

install: make install
script: make coverage && make lint

# @see https://github.com/nickstenning/travis-pip-cache/issues/1
cache: pip
